# Generated by Django 5.1.4 on 2024-12-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=255, verbose_name='Latin Name')),
                ('genus', models.CharField(max_length=255, verbose_name='Genus')),
                ('species', models.CharField(max_length=255, verbose_name='Species')),
                ('french_name', models.CharField(max_length=255, verbose_name='French Name')),
                ('kingdom', models.CharField(max_length=255, verbose_name='Kingdom')),
                ('class_field', models.CharField(max_length=255, verbose_name='Class')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('day', models.DateField(verbose_name='Day')),
                ('continent', models.CharField(max_length=255, verbose_name='Continent')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('region', models.CharField(max_length=255, verbose_name='Region')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('photo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Photo')),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thumbnail')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
            ],
        ),
    ]
