# Generated by Django 5.1.4 on 2024-12-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=255, verbose_name='Nom latin')),
                ('genus', models.CharField(max_length=255, verbose_name='Genre')),
                ('species', models.CharField(max_length=255, verbose_name='Espèce')),
                ('french_name', models.CharField(blank=True, max_length=255, verbose_name='Nom français')),
                ('kingdom', models.CharField(blank=True, max_length=255, verbose_name='Règne')),
                ('class_field', models.CharField(blank=True, max_length=255, verbose_name='Classe')),
                ('order_field', models.CharField(blank=True, max_length=255, verbose_name='Ordre')),
                ('family', models.CharField(blank=True, max_length=255, verbose_name='Famille')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('date', models.CharField(max_length=255, verbose_name='Date')),
                ('continent', models.CharField(blank=True, max_length=255, verbose_name='Continent')),
                ('country', models.CharField(max_length=255, verbose_name='Pays')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Région')),
                ('photo', models.CharField(max_length=255, verbose_name='Photo')),
                ('thumbnail', models.CharField(max_length=255, verbose_name='Vignette')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
            ],
        ),
    ]
