# Generated by Django 5.1.4 on 2025-01-29 21:07

from django.db import migrations

from main.core.load_data.add_data import add_species, add_photos
from main.core.load_data.get_data import get_dataset_on_each_image, get_all_species_data


def insert_initial_data(apps, schema_editor) -> None:
    info_photo = get_dataset_on_each_image()
    latin_name_list = list({value['latin_name'] for value in info_photo})
    info_species = get_all_species_data(latin_name_list, False)
    add_species(info_species)
    add_photos(info_photo)


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
