# Generated by Django 5.1.4 on 2025-01-30 21:07

from django.db import migrations

try:
    from main.core.frontend.create_user import create_local_users
except ImportError:
    def create_local_users():
        pass  # Si aucun fichier d'initialisation est trouvé


def insert_initial_data(apps, schema_editor) -> None:
    create_local_users()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_insert_data'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
