# Generated by Django 5.1.7 on 2025-06-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_collection_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='current_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_users', to='main.collection'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='map_tiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='main.maptiles'),
        ),
    ]
