# Generated by Django 5.1.4 on 2025-01-29 21:07

from django.db import migrations

from main.core.backend.load_data.initialized_database.internal.initialized_database import initialized_database


def insert_initial_data(apps, schema_editor) -> None:
    initialized_database()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
