# Generated by Django 5.1.4 on 2025-01-30 21:07

from django.db import migrations

from main.models.map_tiles import MapTiles
from main.models.theme import Theme


def insert_initial_data(apps, schema_editor) -> None:
    insert_map_tiles()
    insert_themes()


def insert_map_tiles():
    map_tiles_1 = MapTiles.objects.create(name="default", description="Carte par défaut",
                                          server="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png")
    map_tiles_2 = MapTiles.objects.create(name="fr", description="Carte en français",
                                          server="https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png")
    map_tiles_1.save()
    map_tiles_2.save()


def insert_themes():
    theme_1 = Theme.objects.create(name="default", description="Thème encyclopédique", sheet="main-old")
    theme_2 = Theme.objects.create(name="modern", description="Thème moderne", sheet="main-modern")
    theme_1.save()
    theme_2.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
