# Generated by Django 5.1.4 on 2025-01-30 21:07

from django.contrib.auth.hashers import make_password
from django.db import migrations


USERS = [
    ("julsql", "password", "Jul", "SQL", "julsql@email.com")
]


def insert_initial_data(apps, schema_editor) -> None:
    AppUser = apps.get_model('main', 'AppUser')
    Collection = apps.get_model('main', 'Collection')
    CollectionAccounts = apps.get_model('main', 'CollectionAccounts')
    MapTiles = apps.get_model('main', 'MapTiles')
    Theme = apps.get_model('main', 'Theme')

    default_map_tile = MapTiles.objects.first()
    default_theme = Theme.objects.first()

    for username, password, first_name, last_name, email in USERS:
        user_collection = Collection.objects.create(title=f"Collection de {first_name}", owner=None)
        user = AppUser.objects.create(
            username=username,
            password=make_password(password),
            first_name=first_name,
            last_name=last_name,
            email=email,
            map_tiles=default_map_tile,
            theme=default_theme,
            current_collection=user_collection,
        )
        CollectionAccounts.objects.create(collection=user_collection, user=user)
        user_collection.owner = user
        user_collection.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_create_data'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
