# Generated by Django 5.1.7 on 2025-06-10 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from main.models.collection import Collection


def create_collection(apps, schema_editor) -> None:
    collection = Collection.objects.create(title="Une Collection")
    collection.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_create_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('accounts', models.ManyToManyField(related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='current_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='current_users', to='main.collection'),
        ),
        migrations.CreateModel(
            name='MapTiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('server', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='map_tiles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.maptiles'),
        ),
        migrations.RunPython(create_collection),
        migrations.AddField(
            model_name='photos',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rows',
                                    to='main.collection'),
            preserve_default=False,
        ),
    ]
