# Generated by Django 5.2.6 on 2025-12-29 11:14

import django.db.models.deletion
import main.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_create_users'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', main.models.user.AppUserManager()),
            ],
        ),
    ]
