# Generated by Django 5.2.6 on 2026-01-11 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_appuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAction',
            fields=[
                ('upload_id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images_uploaded', models.PositiveIntegerField(default=0)),
                ('images_deleted', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photos',
            name='upload_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_action', to='main.uploadaction'),
        ),
    ]
