# Generated by Django 5.1.4 on 2025-01-30 21:07

from django.db import migrations

from main.models.map_tiles import MapTiles


def insert_map_tiles(apps, schema_editor) -> None:
    map_tiles_default = MapTiles.objects.create(name="default",
                                                description="Carte par défaut",
                                                server="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png")
    map_tiles_default.save()
    map_tiles_fr = MapTiles.objects.create(name="fr",
                                           description="Carte en français",
                                           server="https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png")
    map_tiles_fr.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_collection_appuser_current_collection_and_more'),
    ]

    operations = [
        migrations.RunPython(insert_map_tiles)
    ]
