# Generated by Django 5.1.7 on 2025-06-12 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_create_map_tiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
