# Generated by Django 5.2.6 on 2026-01-11 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_uploadaction_photos_upload_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.uploadaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'seen_at'], name='main_upload_user_id_cbb551_idx')],
                'unique_together': {('upload', 'user')},
            },
        ),
    ]
