# Generated by Django 5.1.7 on 2025-07-21 19:56

import django.db.models.deletion
from django.db import migrations, models


def insert_themes(apps, schema_editor) -> None:
    theme = apps.get_model("main", "Theme")
    theme.objects.create(name="modern", description="Thème moderne")
    theme.objects.create(name="old", description="Thème encyclopédique")

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_appuser_current_collection_alter_appuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RunPython(insert_themes),
        migrations.AddField(
            model_name='appuser',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='main.theme'),        ),
    ]
